# Generated by Django 3.2.8 on 2022-09-20 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email address')),
                ('account_type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], max_length=32)),
                ('hospital', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=32, null=True)),
                ('speciality', models.CharField(blank=True, max_length=32, null=True)),
                ('age', models.CharField(blank=True, max_length=32, null=True)),
                ('weight', models.CharField(blank=True, max_length=32, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('patient_problem', models.CharField(blank=True, max_length=32, null=True)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_contact', models.CharField(max_length=52)),
                ('customer_name', models.CharField(blank=True, max_length=52, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=52, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_contact', models.CharField(max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.CharField(blank=True, max_length=100, null=True)),
                ('property_name', models.CharField(blank=True, max_length=100, null=True)),
                ('property_type', models.CharField(choices=[('Apartment', 'Apartment'), ('Rental', 'Rental'), ('Hostel', 'Hostel'), ('Motel', 'Motel'), ('Retail Shop Space', 'Retail Shop Space')], max_length=52)),
                ('property_location', models.CharField(help_text='Where is the property located ?', max_length=152)),
                ('property_description', models.CharField(blank=True, max_length=200, null=True)),
                ('property_booked', models.BooleanField(default=False, help_text='Has the property been booked or taken ?')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False, help_text='Has the property been verified by admins ?')),
                ('send_property_verification_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partial_payment', models.BooleanField(default=False, help_text='Do you accept partial/installments mode of payment ?')),
                ('additional_info', models.CharField(blank=True, help_text='Any more additional info or specifics about the property ?', max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owner', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_sickness', models.CharField(blank=True, max_length=102, null=True)),
                ('description', models.CharField(blank=True, max_length=102, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=102, null=True)),
                ('start_date', models.DateField(auto_now_add=True, null=True)),
                ('start_time', models.TimeField(auto_now_add=True, null=True)),
                ('verified_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], max_length=52)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
