# Generated by Django 3.2.8 on 2022-10-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20221004_1302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecuitmentAgency',
            new_name='RecruitmentAgency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patient_problem',
        ),
        migrations.RemoveField(
            model_name='user',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weight',
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Worker', 'Worker')], max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
