# Generated by Django 3.2.8 on 2022-10-05 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221004_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='age',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='employer_work_place',
            new_name='employer_work_place_address',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='origin_location',
            new_name='origin_address',
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='work_place_location',
            new_name='work_place_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
