# Generated by Django 3.2.8 on 2022-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221005_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
