# Generated by Django 3.2.8 on 2022-10-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221006_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='abroad',
            field=models.BooleanField(default=False, help_text='Is this worked abroad? '),
        ),
    ]
