# Generated by Django 3.2.8 on 2022-11-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_worker_abroad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentagency',
            name='registration_number',
            field=models.CharField(blank=True, help_text="Agency's licence number.", max_length=52, null=True),
        ),
    ]
