# Generated by Django 3.2.8 on 2022-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20221213_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosisNotes',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
