# Generated by Django 3.2.8 on 2022-12-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20221213_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='signOrSymptom',
        ),
        migrations.AlterField(
            model_name='patient',
            name='occupation',
            field=models.CharField(choices=[('PF', 'Peasant farmer'), ('E', 'Employed'), ('NE', 'Non-employed')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='smokingStatus',
            field=models.CharField(choices=[('S', 'smoker'), ('ES', 'Ex-smoker'), ('NS', 'Non-smoker')], default='NS', max_length=2),
        ),
    ]
